from __future__ import annotations

"""Algorithm constants owned by the image-preprocessing pipeline."""

DEFAULT_MAX_AUTO_DESKEW_DEG = 5.0
DEFAULT_DESKEW_DEAD_ZONE_DEG = 0.12

# Automatic perspective is guarded by analytic-Jacobian distortion and
# before/after text-scale stability. Physical separators remain optional
# structural evidence and do not change this distortion budget.
AUTO_HOMOGRAPHY_HORIZONTAL_SCALE_SPAN_MAX = 0.040
AUTO_HOMOGRAPHY_VERTICAL_SCALE_SPAN_MAX = 0.070
AUTO_HOMOGRAPHY_AREA_SCALE_SPAN_MAX = 0.055
AUTO_HOMOGRAPHY_ANISOTROPY_P95_MAX = 0.035

ORTHOGONAL_AUTO_MIN_CONFIDENCE = 0.45
ORTHOGONAL_AUTO_MIN_SCORE_IMPROVEMENT = 0.25
ORTHOGONAL_AUTO_GAINS = (0.55, 0.70, 0.85, 1.0, 1.10, 1.15)
ORTHOGONAL_MIN_SAFE_GAIN = 0.45
ORTHOGONAL_SCALE_SAFETY_FRACTION = 0.95
ORTHOGONAL_TAIL_PROGRESS_RATIO = 0.90
ORTHOGONAL_TAIL_MAX_REGRESSION_PX = 0.50
ORTHOGONAL_MAX_AUTO_PASSES = 3
POST_PERSPECTIVE_REDETECT_MIN_BOXES = 8
ORTHOGONAL_VERTICAL_MAX_SPAN_MIN_PX = 3.5
ORTHOGONAL_VERTICAL_MAX_SPAN_WIDTH_RATIO = 0.0015
