from __future__ import annotations

"""Static Settings Center metadata.

The dialog keeps compatibility class attributes that reference these exact
objects, while runtime extensions remain free to replace attributes on the
dialog class without creating a dependency back into ``app.py``.
"""

FIELDS = [
        ("词典完整名称", "dictionary_full_name", str),
        ("词典缩写名称", "dictionary_abbreviation", str),
        ("ISBN", "dictionary_isbn", str),
        ("索引语言", "dictionary_index_language", str),
        ("内容语言", "dictionary_content_language", str),
        ("正文页码范围", "dictionary_body_page_range", str),
        ("自定义 Profile 名称", "dictionary_custom_profile_name", str),
        ("词典分栏", "columns", int), ("两栏中隔", "gutter", float),
        ("单栏宽距", "column_width", float), ("起始点 Y", "start_y", float),
        ("正文结束 Y", "bottom_y", int), ("首栏 X", "manual_x", float),
        ("正文缩进", "body_indent", float), ("单行字高", "character_height", float),
        ("行间空白", "row_padding", float), ("向右比例 %", "right_ratio", float),
        ("VB 向右比例 1/x", "ordinary_right_divisor", float),
        ("微调判距", "horizontal_tolerance", float), ("标记线高", "marker_height", int),
        ("垂直线宽", "guide_width", int), ("黑色阈值 RGB 和", "darkness_threshold", int),
        ("候选区域白度上限 %", "dark_area_percent", float),
        ("VB 全白阈值上限", "white_threshold_high", int),
        ("VB 白度阈值下限", "white_threshold_low", int),
        ("VB 白带修正量", "whitespace_adjustment", int),
        ("VB 向上比例 1/x", "upward_ratio", float),
        ("检测后跳步（行高倍数）", "row_step_multiplier", float),
        ("普通分析左边界", "analysis_left", float),
        ("普通分析右边界", "analysis_right", float),
        ("自动保存间隔（秒）", "batch_interval", float),
        ("插图自动识别外扩（px）", "illustration_detect_padding", int),
        ("插图自动识别右侧外扩（px）", "illustration_detect_right_padding", int),
        ("OCR 语言", "ocr_language", str),
        ("Tesseract 语言", "tesseract_language", str),
        ("书写模式", "layout_writing_mode", str),
        ("文字方向", "layout_text_direction", str),
        ("内部版面变换", "layout_transform", str),
        ("栏数策略", "layout_columns_policy", str),
        ("中央分隔线", "layout_column_separator_mode", str),
        ("分析阈值", "analysis_threshold_mode", str),
        ("栏左跟随搜索范围（%栏宽）", "column_track_radius", float),
        ("栏左跟随分块高度（%正文高）", "column_track_block_height", float),
        ("栏左最大局部斜率（%块高）", "column_track_max_step", float),
        ("PaddleOCR 语言", "paddle_language", str),
        ("PaddleOCR 模型版本", "paddle_ocr_version", str),
        ("OCR图像预处理", "paddle_preprocessing", str),
        ("OCR输入最大长边（px）", "paddle_max_input_side", int),
        ("候选带宽比例（%）", "paddle_band_width_ratio", float),
        ("候选带左侧余量", "paddle_band_left_margin", int),
        ("AI 左缘容差", "paddle_left_tolerance", float),
        ("AI 候选置信度", "paddle_rec_score_threshold", float),
        ("AI 同行合并Y比", "paddle_line_merge_y_ratio", float),
        ("AI 字高比阈值", "paddle_height_ratio", float),
        ("AI 粗体比阈值", "paddle_boldness_ratio", float),
        ("AI 行前空白比", "paddle_gap_ratio", float),
        ("AI 最低候选分", "paddle_min_candidate_score", float),
        ("AI 页眉横线搜索高度", "paddle_header_search_height", float),
        ("AI 页眉横线墨迹比例", "paddle_header_rule_ink_ratio", float),
        ("AI 页眉横线后余量", "paddle_header_rule_margin", int),
        ("AI 词性搜索字符数", "paddle_pos_search_chars", int),
        ("横线Y精修搜索范围（行高比）", "paddle_separator_search_ratio", float),
        ("横线Y精修安全带半径（px）", "paddle_separator_band_radius", int),
        ("横线Y精修安全空间（px）", "paddle_separator_safety_px", int),
        ("横线Y精修横向分析范围（%）", "paddle_separator_roi_width_ratio", float),
        ("横线Y精修栏边余量（px）", "paddle_separator_column_margin", int),
        ("Tesseract 对照 PSM", "paddle_tesseract_psm", int),
        ("Google Lens 超时（秒）", "paddle_lens_timeout", int),
        ("Lens无置信度默认值", "paddle_lens_default_confidence", float),
        ("双OCR Y容差（行高比）", "paddle_alignment_y_tolerance_ratio", float),
        ("双OCR 最低lemma相似度", "paddle_alignment_min_similarity", float),
        ("冲突自动选择质量差", "paddle_conflict_review_margin", float),
        ("AI 词头提取正则", "paddle_headword_regex", str),
        ("AI 词性提示正则", "paddle_pos_regex", str),
        ("AI 特殊符号正则", "paddle_special_symbol_regex", str),
        ("主界面字体", "main_entry_font_family", str),
        ("主界面字号（100%）", "main_entry_font_size", int),
        ("主界面词框宽度（字符）", "main_entry_width_chars", int),
        ("主界面词框横向位置（栏宽比例）", "main_entry_x_ratio", float),
        ("校对界面字体", "review_entry_font_family", str),
        ("校对界面字号", "review_entry_font_size", int),
        ("校对文本框上下边距（px）", "review_entry_vertical_padding", int),
        ("校对单字行高（0=中文自动2.5×）", "review_single_cjk_line_height", int),
        ("校对缩放（0=自动适宽）", "review_zoom_percent", float),
        ("wordslist.txt 位置", "wordslist_path", str),
    ]

PROFILE_FIELD_GROUPS = [
        ("Profile v3 版面", [
            "layout_writing_mode", "layout_text_direction", "layout_transform",
            "layout_columns_policy", "layout_column_separator_mode", "analysis_threshold_mode",
        ]),
        ("OCR 与语言", ["ocr_language", "paddle_language", "tesseract_language"]),
        ("版式证据", [
            "columns", "paddle_band_width_ratio", "paddle_band_left_margin", "paddle_left_tolerance",
            "paddle_height_ratio", "paddle_boldness_ratio", "paddle_gap_ratio",
            "paddle_min_candidate_score", "paddle_pos_search_chars",
        ]),
        ("横线定位", [
            "paddle_separator_search_ratio", "paddle_separator_band_radius",
            "paddle_separator_safety_px", "paddle_separator_roi_width_ratio",
            "paddle_separator_column_margin",
        ]),
    ]

PROFILE_CHECKS = [
        ("PaddleOCR 启用文字行方向识别", "paddle_use_textline_orientation"),
        ("候选必须具有结构/视觉提示", "paddle_require_visual_cue"),
        ("候选必须有词性/变形/词条符号", "paddle_require_pos_or_symbol"),
        ("去除词头音节分隔点", "paddle_remove_syllable_separators"),
        ("自动忽略页眉横线以上", "paddle_auto_header_rule"),
        ("词头横线 Y 按栏内墨迹谷精修", "paddle_refine_separator_y"),
    ]

FIELD_GROUPS = [
        ("版面几何", [
            "gutter", "column_width", "start_y", "manual_x",
            "body_indent", "character_height", "row_padding", "right_ratio",
            "horizontal_tolerance", "darkness_threshold",
        ]),
        ("词条线显示", ["marker_height", "guide_width"]),
        ("主界面词条文本框", [
            "main_entry_font_family", "main_entry_font_size", "main_entry_width_chars", "main_entry_x_ratio",
        ]),
        ("词条校对文本框", [
            "review_entry_font_family", "review_entry_font_size", "review_entry_vertical_padding",
            "review_single_cjk_line_height", "review_zoom_percent",
        ]),
        ("辅助词表", ["wordslist_path"]),
        ("列跟踪", ["column_track_radius", "column_track_block_height", "column_track_max_step"]),
        ("插图识别", ["illustration_detect_padding", "illustration_detect_right_padding"]),
        ("OCR 基础", [
            "paddle_ocr_version",
            "paddle_preprocessing", "paddle_max_input_side", "batch_interval",
        ]),
        ("PaddleOCR 候选与版面（高级）", [
            "paddle_rec_score_threshold", "paddle_line_merge_y_ratio",
            "paddle_header_search_height", "paddle_header_rule_ink_ratio",
            "paddle_header_rule_margin",
        ]),
        ("多 OCR / Google Lens", [
            "paddle_tesseract_psm", "paddle_lens_timeout",
            "paddle_lens_default_confidence", "paddle_alignment_y_tolerance_ratio",
            "paddle_alignment_min_similarity", "paddle_conflict_review_margin",
        ]),
        ("词头识别正则（高级）", ["paddle_headword_regex", "paddle_pos_regex", "paddle_special_symbol_regex"]),
    ]

CHECK_GROUPS = [
        ("版面行为", [
            ("使用自动版面参数", "ordinary_auto_layout"),
            ("分栏数", "ordinary_auto_columns"),
            ("正文起始Y", "ordinary_auto_start_y"),
            ("首栏X", "ordinary_auto_manual_x"),
            ("单栏宽", "ordinary_auto_column_width"),
            ("栏间空", "ordinary_auto_gutter"),
            ("单行高", "ordinary_auto_character_height"),
            ("行间空", "ordinary_auto_row_padding"),
            ("跟随词头列倾斜和局部变形", "follow_column_deformation"),
        ]),
        ("OCR 处理", [
            ("OCR 后执行替换", "ocr_replace"), ("OCR 转小写", "lowercase_ocr"),
        ]),
        ("多 OCR 行为", [
            ("Paddle检测同时运行Tesseract对照", "paddle_compare_tesseract"),
            ("Tesseract结果可补漏Paddle词头", "paddle_tesseract_rescue"),
            ("Tesseract自动比较 PSM 4/6", "paddle_tesseract_auto_psm"),
            ("多OCR自动融合决策", "paddle_dual_ocr_arbitration"),
            ("每个OCR左缘候选行显示复选框", "paddle_show_candidate_checkboxes"),
        ]),
        ("校对时主界面", [
            ("主界面显示 OCR 内容选择", "review_main_show_ocr_choices"),
            ("主界面按 OCR 置信度显示底色", "review_main_show_ocr_background"),
        ]),
    ]

OCR_LANGUAGES = ("eng", "spa", "fra", "ita", "por", "deu", "chi_sim", "chi_tra", "jpn", "ara")

SETTING_LABELS = {
        "columns": "正文栏数",
        "start_y": "正文起始 Y",
        "bottom_y": "正文结束 Y",
        "manual_x": "第一栏左缘 X",
        "column_width": "单栏正文宽度",
        "gutter": "栏间空白",
        "character_height": "典型行高",
        "row_padding": "典型行间空白",
        "ocr_language": "词头 OCR 语言",
        "analysis_threshold_mode": "版面墨迹判断方式",
        "body_indent": "正文缩进",
        "character_height": "典型单行字高",
        "row_padding": "典型行间空白",
        "darkness_threshold": "词头锚点黑度阈值",
        "dark_area_percent": "候选区域白度上限",
        "ordinary_right_divisor": "VB 向右比例 1/x",
        "white_threshold_high": "VB 全白阈值上限",
        "white_threshold_low": "VB 白度阈值下限",
        "whitespace_adjustment": "VB 白带修正量",
        "upward_ratio": "VB 向上比例 1/x",
        "analysis_left": "普通分析左边界",
        "analysis_right": "普通分析右边界",
        "row_step_multiplier": "检测后跳步",
        "horizontal_tolerance": "微调判距",
        "column_track_radius": "栏左跟随搜索范围",
        "column_track_block_height": "栏左跟随分块高度",
        "column_track_max_step": "栏左最大局部斜率",
        "paddle_band_width_ratio": "OCR 识别带宽",
        "paddle_left_tolerance": "词头左缘容差",
        "paddle_rec_score_threshold": "OCR 片段最低置信度",
        "paddle_min_candidate_score": "词头候选最低分",
        "paddle_separator_safety_px": "横线与文字安全距离",
        "paddle_line_merge_y_ratio": "同行碎片合并容差",
        "paddle_height_ratio": "字高提示阈值",
        "paddle_boldness_ratio": "粗体提示阈值",
        "paddle_gap_ratio": "行前空白提示阈值",
        "paddle_pos_search_chars": "词性提示搜索范围",
        "paddle_separator_search_ratio": "横线 Y 精修搜索范围",
        "paddle_separator_band_radius": "横线空白带平滑半径",
        "paddle_separator_roi_width_ratio": "横线精修横向范围",
        "paddle_separator_column_margin": "横线精修栏边余量",
        "paddle_max_input_side": "OCR 最大输入边长",
        "paddle_preprocessing": "OCR 图像预处理",
        "paddle_device": "PaddleOCR 运行设备",
        "paddle_ocr_version": "PaddleOCR 模型版本",
        "ocr_executable": "Tesseract 程序路径",
        "batch_interval": "自动保存间隔",
        "wordslist_path": "参考词表文件",
        "dictionary_custom_profile_name": "自定义 Profile 显示名称",
        "detection_method": "默认画线方式",
        "paddle_lens_mode": "Google Lens 运行模式",
        "ocr_engine": "普通文本 OCR 引擎",
        "headword_sort_mode": "词头排序预设",
        "headword_custom_order": "自定义排序单元",
        "headword_custom_fold_accents": "自定义排序重音折叠",
    }

SETTING_HELP = {
        "columns": "作用：正文栏数，是版面几何、阅读顺序、OCR 候选带和后续切图共同使用的基础参数。若【栏数策略】为自动检测，程序会在版面分析时估计栏数；若为固定，则这里的值是权威值。\n\n调整：栏数设错会让栏左缘、词条归栏、阅读顺序和切图边界整体错位。优先用【检测版面参数】和【项目Profile】的代表页结果确认，不建议为修一个局部页面临时改全项目栏数。",
        "gutter": "作用：相邻正文栏之间的典型空白宽度。界面按原图宽度百分比显示和输入，保存/运行时自动换算为当前原图像素。\n\n调整：过小会让相邻栏靠得过近，过大则可能把正文有效区域压窄。通常应由版面检测或 Profile 代表页确定。",
        "column_width": "作用：单栏正文的典型宽度。界面按原图宽度百分比显示和输入，后台在运行前换算为原图像素；它决定栏几何的水平范围，并间接影响 OCR 候选带、词条矩形和相邻栏边界。\n\n调整：过小可能截掉长词头/释义并让切图偏窄；过大可能侵入栏间空白甚至邻栏。",
        "start_y": "作用：正文起始 Y。界面按原图高度百分比显示和输入，0% 为图片顶部、100% 为图片底部；后台自动换算为原图 Y 像素供版面分析与画线使用。\n\n若 Project Profile 明确设置页眉模式/页眉比例，页面模板仍可为当前页计算实际正文上界。",
        "bottom_y": "兼容字段：普通页面不再把【正文结束 Y】作为常用手工参数。只有【项目Profile】明确设置页尾时，运行时才会为当前页解析有效正文下界；旧项目中的 bottom_y 仍可读取以保持兼容。最终切图下边界请在【切图设置】中调整。",
        "manual_x": "作用：第一栏左缘 X。界面按原图宽度百分比显示和输入，0% 为图片左边、100% 为图片右边；后台自动换算为原图 X 像素。其余栏位置结合栏宽、栏间距推导。\n\n镜像、RTL、竖排等阅读方向只影响内部读取顺序/临时变换，不改变百分比相对于原图边界的定义。",
        "body_indent": "作用：普通画线把它作为 VB.NET 原版【正文缩进】先验。界面按原图宽度百分比输入，后台换算为原图像素后用于二维墨迹确认和栏左跟踪。\n\n调整：应接近释义正文相对词头栏左缘的真实缩进。过小会让二维确认范围不足；过大则会引入更多上下邻行墨迹，但候选锚点仍受【微调判距 < 正文缩进】约束。",
        "character_height": "作用：项目的典型单行字高。界面按原图高度百分比显示和输入，后台换算为原图像素；普通画线、OCR 行距/空白判断、横线 Y 精修和部分 CJK 视觉逻辑都以它作为尺度基准。\n\n调整：应接近正文常规印刷行高，而不是某个特别大的词头字高。",
        "row_padding": "作用：典型行周围的额外留白尺度。界面按原图高度百分比输入，后台换算为原图像素后参与普通画线行盒、词条单行框高度以及 OCR 词头前空白/分隔位置等计算。\n\n调整：增大可给文字上下更多安全空间，但过大会让相邻行更容易重叠/合并；过小则可能让横线或单行切图贴字过紧。应和【典型行高】一起校准。",
        "right_ratio": "作用：词条单行矩形向右覆盖当前栏宽的百分比；当前实现会限制在 1%–100%。它主要影响词条矩形/单行切图的水平覆盖，不决定 OCR 是否把某行识别为词头。\n\n调整：减小可避免把过多释义或邻近内容纳入单行框；增大可保留更完整的同行上下文。它属于历史兼容参数，目前不在设置中心常用分组中，最终导出范围仍应以【切图设置】为准。",
        "horizontal_tolerance": "作用：严格对应 VB.NET Draw_Auto 的【微调判距】。界面按原图宽度百分比输入，后台换算为原图像素；普通画线在每个原图 Y 上，从当前动态栏左 LX(y) 开始向正文方向扫描到该距离。\n\n调整：数值太小会漏掉略微右移的真实词头，太大则会把正文起笔纳入锚点通道。旧项目保存的像素值会在界面中按当前原图宽度自动换算为百分比。",
        "analysis_threshold_mode": "作用：控制版面检测、栏位分析和倾斜/弯曲跟踪时如何把灰度转成墨迹。普通画线的最终词头锚点为保持同一本词典跨页稳定，重新使用独立的【词头锚点黑度阈值】；因此 auto/Otsu/adaptive 不再替代这个锚点门槛。\n\n选择：版面底色正常时保持 auto；阴影或书脊亮度明显不均时可试 adaptive。它主要影响版面几何，不应再拿来补偿普通词头误检。",
        "darkness_threshold": "作用：普通画线恢复 VB.NET 的固定词头黑色锚点门槛。RGB 和低于该值的像素才有资格成为栏左词头起点；默认 300 相当于灰度约 100。这个门槛跨页固定，不随每页 Otsu 分布漂移。\n\n调整：提高可接受更浅的印刷，但也更容易让灰噪声成为锚点；降低更严格。它只负责找到词头起点，随后还必须通过二维【候选区域白度上限】确认。",
        "dark_area_percent": "作用：对应 VB.NET IsPoint。找到栏左黑色锚点后，在原图上检查向正文方向【正文缩进 × 2×正文缩进】的二维区域，按原 VB 分母规则计算平均亮度；高于该百分比就拒绝。默认 90%。\n\n这一步与栏左锚点是两个独立门：前者限制起点位置，IsPoint 再确认附近确实存在一块词头文字。",
        "ordinary_right_divisor": "作用：这是恢复出来的 VB.NET【向右比例 1/x】，只服务普通画线的横向白带分析，和当前【向右比例 %】词条框宽度完全分离。实际分析宽度约为 单栏宽 / 本值 × 0.98；默认 1.0，即检查接近整栏的 98%。\n\n值越大，Y 分隔判断看的横向范围越窄。不要用它调词条切图宽度。",
        "white_threshold_high": "作用：VB 白带定位的上限阈值，采用原版 0–1000 行亮度尺度，默认 999。完全找不到第一阶段的无黑点横行时，第二阶段从这里开始逐级放宽。\n\n通常保持 999；降低会更早接受带少量墨迹的横行。",
        "white_threshold_low": "作用：VB 白带定位逐级放宽的下限，默认 700。算法按 999、997、995……一直降到本值，寻找窄行距、轻微歪斜或上下伸字符之间仍足够亮的分隔行。\n\n过低可能把文字内部亮带误当行间空白。",
        "whitespace_adjustment": "作用：对应 VB.NET 的白带修正量，默认 2 px。第一阶段找到白行后会检查其上方连续高白度行并向白带中部修正；第二阶段也用它处理极窄行间隙和局部歪斜。单位始终是原图像素。",
        "upward_ratio": "作用：对应 VB.NET【向上比例 1/x】。从词头黑锚点向上搜索分隔线的最大距离 = (单行字高 + 行间空白) / 本值；默认 1.5。\n\n值越大，向上搜索范围越短；过短会找不到上一行与当前词头之间的白带。",
        "analysis_left": "作用：普通画线分析区域的左边界。界面按页面宽度百分比显示和输入，0% 为图片最左侧；后台保存和运行时仍换算为当前原图 X 像素。与右边界同时有效且右>左时，栏左锚点和横向白带分析只在该范围内工作；左、右都为 0% 时表示不额外限制。\n\n调整：只有需要排除装订边、页边注释或固定非正文区域时才建议修改。使用百分比后，不同 DPI 或扫描宽度下保持相同版面含义。",
        "analysis_right": "作用：普通画线分析区域的右边界。界面按页面宽度百分比显示和输入，100% 为图片最右侧；后台运行时换算为当前原图 X 像素。与左边界配合限制普通画线分析区域。\n\n调整：应覆盖全部正文栏而排除稳定的页边非正文内容。若保持历史默认 0/0，则继续表示整页分析，不强制裁定分析范围。",
        "row_step_multiplier": "作用：对应 VB.NET 找到候选并确定分隔 Y 后的跳步。下一次扫描从【当前分隔 Y + (单行字高+行间空白) × 本值】附近继续；默认 1.2。这样同一个词头的多个笔画和紧邻正文不会再次触发。",
        "column_track_radius": "作用：开启【跟随栏左缘倾斜/弯曲】后，搜索范围按当前页当前栏的实际栏宽计算：搜索半径 = 单栏宽 × 本百分比。默认 5%。因此不同 DPI、不同裁边或逐页自动版面参数下仍保持同一几何含义。\n\n调整：过小会跟不上明显倾斜/弯曲；过大则可能把正文缩进或邻栏墨迹吸进搜索走廊。",
        "column_track_block_height": "作用：沿正文有效高度分块跟踪栏左缘：分块高度 = 当前页正文有效高度 × 本百分比。默认 3%，即通常把正文纵向分成约 30 多段。\n\n调整：太小容易受单个粗字、插图和污点影响；太大则会把真实局部弯曲过度拉平。",
        "column_track_max_step": "作用：相邻跟踪锚点允许的最大横向变化改为局部斜率：最大步移 = 当前分块高度 × 本百分比。默认 8%。这样即使改变扫描分辨率或分块高度，允许的几何斜率仍保持一致。\n\n调整：过小会把真实倾斜强行拉直；过大则更容易被缩进正文或异常墨迹带偏。",
        "ocr_language": "作用：项目的主要词头/OCR语言，是多个组件的上层语义入口：用于选择/映射 PaddleOCR 与 Tesseract 语言、Dictionary Profile 默认结构、排序预设以及部分 CJK/拉丁解析路径。\n\n调整：应填写词头语言而不是释义语言。改变后可能导致 OCR 模型、Profile 和排序语义变化，已有 OCR 缓存/结果不应默认视为仍可比较，稳定项目中不要频繁切换。",
        "paddle_device": "兼容字段：旧项目中的 CPU/GPU 值继续读取，但运行时设备现在由本机环境自动决定，不再作为可迁移的项目参数。高级用户可用 PICTURE_CAPTURE_PADDLE_DEVICE=cpu/gpu 临时强制本机设备。",
        "paddle_preprocessing": "作用：决定送入 PaddleOCR 前的图像预处理。original 保留原图；grayscale 转灰度；auto_contrast 拉伸对比度；binary 强制二值化。\n\n选择：默认优先 original，因为 OCR 模型通常能利用原始灰度/颜色信息。只有扫描发灰、底色不均或模型确有改善证据时再改；过度二值化可能损失细笔画和重音符号。",
        "paddle_max_input_side": "作用：限制送入 PaddleOCR 的图像最大长边，超出时按比例缩小。它主要平衡小字细节、推理速度、内存/显存和模型稳定性。\n\n调整：增大可保留更多细节，但会更慢、更占显存；减小更省资源但可能让小字号/附加符号变糊。改变此项会改变 OCR 输入图像，应视为可能需要重新 OCR，而不仅是重新评分候选。",
        "paddle_band_width_ratio": "作用：当前实际检测单栏宽度中，有多少百分比从栏左侧进入 OCR 候选带。100% 就是当前栏完整宽度；【候选带左侧余量】是在这个百分比之外另加的安全边距，不再以历史固定 600px 作为 100%。\n\n调整：太小会截断长词头、性别变体或紧随其后的 POS；太大则会引入更多释义正文、增加耗时和误候选。该比例随实际栏宽/DPI 自适应。",
        "paddle_band_left_margin": "作用：在 OCR 候选带左侧额外向外扩出的距离，单位为原图像素，用于保留略越出估计栏左缘、装饰符号或列跟踪误差附近的文字。运行时不做 1400px 或页面宽度归一化。\n\n调整：增加可救回被左边界裁切的词头；过大则会纳入页边线、污点或上一栏区域。",
        "paddle_left_tolerance": "作用：词头候选允许偏离估计栏左缘的最大距离。界面按当前单栏正文宽度的百分比显示和输入，后台仍保存/运行原图像素值，因此同一版式在不同扫描 DPI 下具有一致含义。\n\n调整：增大可容纳缩进词头，但也更容易把正文缩进行吸进候选；减小更严格。通常先保持 Profile 推荐值，仅在真实词头系统性偏离栏左缘时调整。",
        "paddle_rec_score_threshold": "作用：在 OCR 碎片完成必要的同行/结构修复后，按识别置信度过滤低质量 OCR 行。低于阈值的行不会继续进入词头候选评分。\n\n调整：降低可提高召回、救回难字/粗体/重音符号，但会带入更多噪声；提高则更干净但更容易漏词。它和【词头候选最低分】不同：前者是 OCR 文字质量门槛，后者是综合结构评分门槛。",
        "paddle_line_merge_y_ratio": "作用：将同一印刷行被 OCR 拆成多个 box 时，允许多大的垂直差仍合并为一行。词头、性别变体和 POS 经常被模型拆成多个片段，因此这一步发生在后续语法解析之前。\n\n调整：增大可合并错开的碎片，但过大会把上下两行粘在一起；减小可避免串行，却可能让词头与 POS 分离。出现“同一行被拆开/上下行被合并”时才针对性调整。",
        "paddle_height_ratio": "作用：把候选行字高与页面候选行中位字高比较；达到该比例后获得“较大字”视觉提示并增加候选分。它是辅助证据，不是独立接受条件。\n\n调整：提高会让“字大”证据更难触发；降低会让更多正文也被视为大字。仅当词头确实通过字号区别于正文时才值得调，结构证据通常比字号更可靠。",
        "paddle_boldness_ratio": "作用：比较候选行前部墨迹密度与页面局部基准，达到该比例后获得“粗体/更黑”视觉提示并增加候选分。正文中的标签也可能粗体，所以它不是最强证据。\n\n调整：提高更严格、误触发少；降低更敏感，但扫描阴影/对比度变化会带来假粗体。应结合诊断中的 boldness_ratio，而不是仅凭肉眼猜测。",
        "paddle_gap_ratio": "作用：以“典型行高 + 行间空白”为尺度，判断当前候选前方是否存在足够大的纵向空白；满足时作为词条起始的弱视觉证据加分。\n\n调整：提高意味着需要更大的前置空白才算 separated；降低会让较小行距也触发该证据。它只贡献较弱分值，不应拿它替代 POS/变形等结构证据。",
        "paddle_min_candidate_score": "作用：候选在完成 lemma 解析、栏左位置、POS/变形/描述符、特殊符号、字高、粗体和行前空白等加权后，必须达到的综合最低分。\n\n调整：提高会减少误检但增加漏检；降低会提高召回但放入更多边缘候选。不要在不知道 reject_reason/score 构成时盲目下调；优先看 diagnostics 是缺结构、位置不对还是单纯分数不足。",
        "paddle_header_search_height": "作用：自动页眉横线检测只在页面顶部指定范围内搜索。界面按页面高度百分比显示和输入，后台运行时换算为当前原图 Y 像素。超出该范围的横线不会被当作页眉规则线。\n\n调整：页眉线位置较低时可适当增大；过大可能把正文中的表格线、装饰线或词条分隔线误当页眉。不同 DPI/扫描高度下建议保持相同百分比，而不是固定像素。",
        "paddle_header_rule_ink_ratio": "作用：在页眉搜索区逐行计算黑色墨迹占比，达到该比例的行才有资格被视为贯穿式页眉横线。当前实现会把输入限制在合理范围后使用。\n\n调整：提高更严格，需要更长/更实的横线；降低可识别断裂或浅色横线，但也更容易把文字行误判为横线。只有【自动忽略页眉横线以上】开启时才有意义。",
        "paddle_header_rule_margin": "作用：识别到页眉横线后，再向正文方向额外留出的安全距离，单位为原图像素。该值不再按页面宽度缩放。\n\n调整：增大可避免页眉残留，但可能吃掉第一条正文词头；减小则更贴近横线。",
        "paddle_pos_search_chars": "作用：lemma 提取后，语法解析在其后的多长文本范围内寻找 POS/变形等结构提示。这样可利用近邻语法标签，同时避免把很后面的释义正文缩写误当词头证据。\n\n调整：长词头、长性别变体或 POS 距离较远时可适当增大；过大可能在定义正文里误命中缩写。存在活动 Dictionary Profile 时，POS 标签集合通常由 Profile 的 pos_labels 决定。",
        "paddle_separator_search_ratio": "作用：OCR 粗定位词头 Y 后，以典型行高为尺度，在其附近上下搜索更合理的空白带/分隔位置，从而把横线从文字框位置精修到视觉上的行间空白。\n\n调整：增大搜索更宽，能修正较大的 OCR Y 偏差，但更可能跳到相邻行；减小更保守。只有【自动精修横线 Y】开启时才直接影响结果。",
        "paddle_separator_band_radius": "作用：横线 Y 精修时，对局部墨迹/空白曲线做平滑的半径，单位为原图像素。该值不再使用 1400px 参考宽度。\n\n调整：增大更平滑但可能抹掉窄空白带；减小更敏感但更受噪声影响。",
        "paddle_separator_safety_px": "作用：横线精修后与当前词头墨迹之间保留的额外安全距离，单位为原图像素。设置 2 就始终是原图 2 px，不随页面宽度变化。\n\n调整：文字被线贴住/穿过时增大；横线与词头间距明显过大时减小。",
        "paddle_separator_roi_width_ratio": "作用：横线 Y 精修时，只分析当前栏左侧一定百分比的横向区域，而不是整栏释义。这样可减少右侧长定义、插图或其他墨迹干扰。\n\n调整：减小更聚焦词头附近；太小可能只看到少量字符而不稳定。增大提供更多墨迹统计，但正文干扰也增加。",
        "paddle_separator_column_margin": "作用：横线精修分析时，从栏最左边缘跳过一小段区域，避免栏边线、装订阴影、竖直装饰线被误当作文字墨迹。单位为原图像素，不按页面宽度缩放。\n\n调整：存在明显栏线/黑边时可增大；过大会跳过真正贴边的词头。",
        "paddle_tesseract_psm": "作用：Tesseract 对照 OCR 的 Page Segmentation Mode。当前词头候选带常见 PSM 6（单一均匀文本块）与 PSM 4（单栏但行/字号更灵活）；若开启【自动比较 PSM 4/6】，程序会自行比较，不必手动固定。\n\n调整：只有 Tesseract 对照结果明显分行错误且自动比较关闭时才改。它不影响 PaddleOCR。",
        "paddle_lens_language": "Google Lens OCR 语言自动跟随【词头 OCR 语言】，不再单独配置。Profile 或 OCR 语言变化时会同步更新。",
        "paddle_lens_timeout": "作用：一次 Google Lens 网络 OCR 最长等待时间。超时后该次 Lens 结果会失败/缺失，但本地 Paddle/Tesseract 流程仍可继续。\n\n调整：网络慢而频繁超时时可增大；过大则在服务不可达时等待更久。Lens 是可选网络依赖，不建议用超长超时掩盖网络配置问题。",
        "paddle_lens_default_confidence": "作用：Lens 没有提供可直接比较的真实置信度时，给它一个用于多 OCR 质量比较的默认值。这个数会影响 Lens 在可投票模式下的相对权重。\n\n调整：提高会让无置信度 Lens 结果更容易与本地 OCR 竞争；降低则更保守。除非已系统评估 Lens 在本项目上的可靠性，否则保持默认。",
        "paddle_alignment_y_tolerance_ratio": "作用：Paddle 与 Tesseract/Lens 候选做跨引擎配对时，允许它们在 内部阅读方向 上相差多少个典型行高。只有位置足够接近的候选才可能被认为是同一词头。\n\n调整：增大可配对 Y 偏差较大的结果，但可能把相邻两条词头错配；减小更严格但会增加“各自独立候选”。",
        "paddle_alignment_min_similarity": "作用：跨 OCR 候选除位置外，lemma 文本相似度还需达到该最低值才优先视为同一候选。它帮助避免 Y 相近但实际上是不同词头的错误合并。\n\n调整：提高更严格、错配少但 OCR 字符误差较大时难配对；降低能容忍更多识别差异但可能错误合并。应结合 comparison/fusion 报告调。",
        "paddle_conflict_review_margin": "作用：当多个 OCR 给出的质量分接近时，用这个“质量差阈值”决定是否把结果标成需要人工复核。当前逻辑中，质量差小于该值更容易进入 review。\n\n调整：增大意味着更多近似甚至中等差异的冲突进入人工复核；减小则只有非常接近的结果才提示 review。它影响复核负担，不是 OCR 字符识别阈值。",
        "paddle_headword_regex": "作用：从每个合并后的 OCR 候选行开头提取 lemma（词头文字）。匹配成功后，若正则含捕获组，程序取第 1 个捕获组作为原始词头；它只是“词头像不像一个合法字符串”这一关，最终是否接受仍会结合栏左位置、词性/变形/符号、视觉分数和 Profile 规则。\n\n默认：允许行首空格及可选的 • ◆ ◇ ► ▶ * † ‡ § ¶；允许前/后置连字符、Unicode 字母、音节分隔点 · • ∙ ‧，并容忍 OCR 把分隔点识成 . : + -；也允许撇号连接。例如“• a·ga·rrón s. m.”提取 a·ga·rrón，“anti- adj.”提取 anti-。\n\n修改：第 1 捕获组应只包住 lemma。写得过宽会把逗号、POS/正文吞入词头；过窄会在后续评分前直接漏词。默认 Latin Profile 还会把通用 Unicode 字母范围收窄为拉丁字母；项目特例优先用 Profile 或过滤规则。",
        "paddle_pos_regex": "作用：识别 lemma 后面的 POS/语法标签，作为“这一行确实是词条起始行”的强结构证据；它不负责提取 lemma，搜索范围还受【AI 词性搜索字符数】限制。\n\n默认兼容：可覆盖 s.、s. m./f./amb./pl.、adj./adj. inv.、adv.、v./y.、v. prnl.、prep.、conj.、pron. 子类、det.、interj.、art.、num.、loc.、superlat. 等；y. 是容忍 OCR 把 v. 识成 y.。\n\n重要：主程序加载活动 Dictionary Profile 时，实际 POS 正则由 Profile 的 pos_labels 动态生成，本字段主要是兼容/低层 fallback。当前项目要增删词性缩写应优先改 Profile grammar。",
        "paddle_special_symbol_regex": "作用：判断 OCR 行首是否出现“可作为新词条起始证据”的项目符号。命中只增加一项结构证据，不会无条件把该行接受为词头。\n\n默认只在行首（允许前导空格）识别 • ◆ ◇ ► ▶ * † ‡ § ¶。正文中间出现同样符号不会命中。\n\n修改：只加入真正表示新词条/新条目起始的符号。词条内部释义标记、交叉引用或文章结构符号应交给 Dictionary Profile；例如某些词典中的 ■、□、||、~、→ 属于内部结构，不应因此触发新 lemma。",
        "ocr_executable": "兼容字段：旧项目中的 Tesseract 路径仍会作为发现提示读取，但新的可执行程序选择保存为本机 runtime 设置，不再随项目迁移。请在【环境中心】中选择或重新检测 Tesseract。",
        "paddle_ocr_version": "作用：选择 PaddleOCR 使用的模型系列/版本。不同模型可能改变文字框、识别字符、速度和缓存签名，因此它属于后端级设置而不是单纯阈值。\n\n调整：项目一旦稳定不建议频繁切换。更换模型后应重新生成 OCR，而不是继续沿用旧缓存来比较候选规则。",
        "tesseract_language": "作用：Tesseract 使用的语言包代码，可与项目 OCR 语言不同但通常应对应词头语言。它用于普通文本 OCR和 Tesseract 对照/补漏路径。\n\n调整：若语言包未安装，Tesseract 会不可用或报错；多语言可按 Tesseract 语法组合。仅使用 PaddleOCR 时不会因为这个值改变 Paddle 结果。",
        "batch_interval": "作用：自动保存/批量相关状态写盘的节流间隔，用来避免每次微小编辑都立即写文件。它影响保存频率，不是 OCR 批量任务“每隔几秒处理一页”的间隔。\n\n调整：过短增加磁盘写入和界面抖动风险；过长则异常退出时可能丢失更多最近改动。通常保持数秒级即可。",
        "marker_height": "作用：主界面词头横线的显示线宽/可视厚度，绘制时会按当前界面缩放和旧项目兼容比例调整。它影响视觉与点击辨识，不改变词头 Y 坐标或 OCR 判定。\n\n调整：高 DPI/高缩放下看不清可适当增大；过粗会遮挡文字。属于纯显示参数。",
        "guide_width": "作用：主界面栏左参考线/列路径的显示宽度。只控制视觉叠加层，不改变列跟踪、栏位置或切图数据。\n\n调整：为了在高分辨率屏幕上更易观察可增大；如果参考线遮挡正文则减小。识别结果不应随它变化。",
        "main_entry_font_family": "作用：主界面可编辑词条文本框与部分预览标签使用的字体族。只改变显示/编辑体验，不修改 PDIC 文本、OCR 结果或排序。\n\n选择：【自动（系统推荐）】会根据当前 OCR 语言和操作系统选择原生/常用无衬线字体；手动选择任一已安装字体后则固定使用该字体。若出现方框/缺字，应换字体而不是修改 OCR。",
        "main_entry_font_size": "作用：主界面词条编辑框在 100% 视图下的基础字号；实际显示会结合当前视图缩放。只影响界面文字大小，不改变图像坐标、词条线或切图。\n\n调整：增大便于校对但会占更多画布空间；过小影响阅读。它与图片缩放是两套独立概念。",
        "main_entry_width_chars": "作用：主界面词条编辑控件的目标宽度，以字符数估算；横排时主要控制 Entry 宽度，竖排模式则用于窄 Text 控件的可见长度/高度语义。\n\n调整：长词头经常看不全可增大；过大会遮挡原图。只影响编辑控件，不改变词条内容。",
        "main_entry_x_ratio": "作用：主界面词条编辑框相对当前栏宽的横向放置比例，用来把文本框挪到更不遮挡原图的位置。位置换算会考虑 layout transform/RTL。\n\n调整：只改变 GUI 叠加位置；不会修改 entry.x/PDIC 坐标或识别结果。不同版式遮挡严重时再调。",
        "review_entry_font_family": "作用：校对窗口中“原词条”编辑框使用的字体，与主界面字体和简体伴随列字体相互独立。只影响显示和字符宽度测量。\n\n选择：【自动（系统推荐）】会根据当前 OCR 语言和操作系统选择字体；手动选择后固定使用该字体。字体应完整覆盖重音字母/CJK/特殊符号；字体变化可能改变编辑框按裁图宽度换算出的可见字符数，但不会修改保存文字。",
        "review_entry_font_size": "作用：校对窗口原词条编辑框固定字号；校对图片缩放不会自动把这个字号一起放大/缩小。这样可独立控制图片细节和文字编辑可读性。\n\n调整：增大便于阅读，但同一宽度能显示的字符数减少；减小反之。只影响界面。",
        "review_entry_vertical_padding": "作用：校对文本框内部上下对称留白（像素），主要用于避免重音、上标/下延部或特殊字体被单行 Entry 裁切。\n\n调整：字符顶/底被切时增大；过大会让每行校对控件显得过高。它不改变行高模型、图片裁图或 PDIC。",
        "review_single_cjk_line_height": "作用：校对窗口针对中文单字词条使用的特殊裁图行高。0 表示自动按项目典型行高约 2.5 倍计算；非 0 时单位为原图像素。\n\n调整：单字大字头被上下裁掉时增大；留白过多时减小。只影响校对裁图展示，不改变词头检测位置。",
        "review_zoom_percent": "校对切条图片默认使用自动适宽：0 表示按校对窗口左侧实际图片区宽度自动计算，使切条图片占约 99%。手动输入百分比或使用 +/- 后切换为手动缩放；点击【自动】可恢复自动适宽。",
        "wordslist_path": "作用：指定参考 wordslist.txt，用于主界面/校对界面的“是否已在词表中”、定位和新旧比较等辅助判断。程序使用成员索引，不要求把整份大词表一次渲染到 GUI。\n\n路径：项目内文件优先保存相对路径便于迁移；项目外文件使用绝对路径。它是校对参考源，不会反向修改 OCR 识别结果。",
        "illustration_detect_padding": "作用：自动插图检测得到初始 PPP 轮廓/边界后，四周统一额外扩出的原图像素，用于避免图像主体贴边被裁掉。\n\n调整：插图边缘经常缺失可增大；过大会吞入正文。",
        "illustration_detect_right_padding": "作用：在通用插图外扩之外，右侧再额外扩展的原图像素。用于某些词典插图常向栏间或右侧空白延伸的版式。\n\n调整：只在右侧经常被截时增加；过大会把邻近文字纳入插图。",
        "dictionary_full_name": "作用：当前词典的完整名称，属于项目元数据，用于项目详情、后期词典制作和导出信息。不会改变 OCR、画线或排序算法。\n\n填写：建议使用正式书名而不是本地文件夹名；后续打包/共享项目时更容易识别来源。",
        "dictionary_abbreviation": "作用：词典缩写/短名，供 PicDic、导出命名或项目元数据使用。它不参与识别。\n\n填写：应稳定、简短且避免频繁变化；如果下游格式使用它作为标识，修改后需注意旧导出物与新导出物的一致性。",
        "dictionary_isbn": "作用：可选的 ISBN 项目资料，用于来源记录和后期词典元数据，不参与任何 OCR/版面判断。\n\n填写：没有 ISBN 或版本不确定时可留空；不要为了通过设置校验填伪值。",
        "dictionary_index_language": "作用：词头/索引语言的 ISO 639-1 两位代码，用于后期词典元数据、索引/排序语义等项目层信息。首次可根据 OCR 语言自动建议，但之后用户选择应被保留。\n\n注意：它描述“索引词是什么语言”，不等同于释义内容语言，也不直接替代 OCR 引擎自己的语言代码。",
        "dictionary_content_language": "作用：释义/正文内容语言的 ISO 639-1 两位代码，用于后期词典元数据。双语词典中它通常和索引语言不同。\n\n注意：它不负责选择 OCR 模型，也不会改变词头排序；请按词典内容语义填写。",
        "dictionary_body_page_range": "作用：记录词典正文的页码范围，例如 1-1250。Project Profile 选择代表页、批量工作流或后续制作步骤可据此区分正文与前后附页。\n\n填写：使用逻辑正文页范围，而不是操作系统文件序号；范围错误可能让代表页/批量流程包含封面、索引或附录。",
        "dictionary_custom_profile_name": "作用：仅给当前项目的“自定义结构”Profile 一个更易读的显示名称；底层 Profile key 仍保持 custom，解析器和持久化身份不会因此改变。\n\n适用：当你为某本特殊词典建立了自定义结构时，可用书名/版式名标记。它不是新建一个新的内置 Profile，也不会自动改变任何识别规则。",
        "layout_writing_mode": "作用：定义页面文字的书写方式，例如横排或竖排，并影响阅读顺序和内部图像分析方向。\n\n坐标规则：无论选择哪种书写方式，用户设置、PDIC/PPP 和对外坐标始终只保存原图 X/Y；内部临时旋转/镜像不会建立第二套持久化坐标。",
        "layout_text_direction": "作用：定义阅读方向，例如横排 LTR/RTL。它影响栏顺序、阅读顺序和某些界面/导出排序。\n\n坐标规则：阅读方向不会改变设置值的原图 X/Y 语义。",
        "layout_transform": "作用：内部分析时可对原图做临时 identity/mirror/rotate 变换，以统一阅读顺序。\n\n坐标规则：这是内部处理方式，不是第二套用户坐标。所有设置和最终结果在离开内部处理边界前都回到原图 X/Y。",
        "layout_columns_policy": "作用：决定栏数是由版面检测自动估计（detect）还是固定使用项目设置值（fixed）。\n\n选择：不同页面栏数稳定且检测容易受插图/空白干扰时可固定；版式可能变化或希望按实际页面估计时用 detect。fixed 下【正文栏数】尤为关键。",
        "layout_column_separator_mode": "作用：告诉版面检测中央/栏间是否存在明显分隔线：auto 自动判断，present 明确存在，absent 明确没有。该信息会改变栏边搜索区域和分隔线检测策略。\n\n选择：有稳定印刷竖线时 present 可减少歧义；明确无竖线时 absent 避免程序为不存在的线留搜索空间；不确定保持 auto。",
        "paddle_language": "作用：PaddleOCR 后端使用的语言/模型代码。通常由上层【OCR 语言】映射得到，属于后端专家覆盖项。\n\n修改：只有默认映射不适合当前模型或在调试 PaddleOCR 后端时才手动指定。与项目主语言不一致可能显著降低识别率，并可能改变 OCR 缓存签名。",
        "detection_method": "作用：设置主界面默认使用哪条“画线”路径。融合画线（推荐）让普通几何检测与 OCR 语义检测独立产生候选，再按同栏 Y 位置一对一配对、继承 OCR 文字并严格去重；OCR 或普通模式仍可单独运行用于诊断。\n\n选择：日常优先融合画线；需要判断问题究竟来自几何规则还是 OCR/parser 时，再分别运行单独模式。",
        "paddle_lens_mode": "作用：控制 Lens 在启用后的调用范围和是否参与融合。off 不调用；diagnostic 可全量获取但 Lens 不投票；conflict 只在 Paddle/Tesseract 冲突或缺失时调用；full 可对更多候选调用并影响非冲突决策。\n\n选择：推荐 conflict，能把网络调用集中在真正有价值的疑难项。full 最耗网络且会让 Lens 对更多最终结果产生影响。",
        "ocr_engine": "作用：这是“已有词条线后再识别整行文本”的普通 OCR 引擎设置，与 OCR画线的多引擎词头检测不是同一件事。\n\n选择：Tesseract/PaddleOCR 只影响普通文本填充路径；不要因为这里选了 Tesseract 就以为 OCR画线也只使用 Tesseract，后者由 OCR画线页的独立开关控制。",
        "headword_sort_mode": "作用：决定校对/索引检查采用的词头排序规则。可随 OCR 语言提供语言专用预设，也可使用通用 Unicode 或自定义字母表。\n\n注意：排序只改变比较/显示顺序和索引语义，不会改变扫描页面物理顺序、PDIC 坐标或 OCR 文字。",
        "headword_custom_order": "作用：当排序预设选择“自定义”时，这里定义词典自己的排序单元，空格分隔；允许 ch、ll、dz 等多字符单元。\n\n填写：顺序就是排序优先级。遗漏的字符会按后备规则处理，因此应覆盖该词典真正需要特殊排序的字母/多字符单元，而不是照抄无关语言字母表。",
        "headword_custom_fold_accents": "作用：仅在自定义排序中使用。开启后，没有在自定义顺序里单独列出的重音字母会按其基础字母折叠排序；关闭则保留它们的独立字符差异。\n\n选择：如果词典把 á/é/ñ 等视作独立排序单位，应显式列入自定义顺序或关闭折叠；若只把重音视作基本字母变体则可开启。",
    }

COMMON_FIELDS = (
        "columns", "start_y", "manual_x", "column_width", "gutter",
        "character_height", "row_padding", "ocr_language",
    )

NORMAL_COMMON_FIELDS = (
        "body_indent", "horizontal_tolerance", "character_height", "row_padding",
    )

NORMAL_ADVANCED_FIELDS = (
        "analysis_threshold_mode", "darkness_threshold", "dark_area_percent",
        "ordinary_right_divisor", "white_threshold_high", "white_threshold_low",
        "whitespace_adjustment", "upward_ratio", "row_step_multiplier",
        "analysis_left", "analysis_right",
        "column_track_radius", "column_track_block_height", "column_track_max_step",
    )

OCR_COMMON_FIELDS = (
        "ocr_language", "paddle_preprocessing",
        "paddle_band_width_ratio", "paddle_left_tolerance",
        "paddle_separator_safety_px",
    )

OCR_ADVANCED_FIELDS = (
        "paddle_max_input_side", "paddle_band_left_margin",
        "paddle_rec_score_threshold", "paddle_line_merge_y_ratio",
        "paddle_height_ratio", "paddle_boldness_ratio", "paddle_gap_ratio",
        "paddle_min_candidate_score", "paddle_header_search_height",
        "paddle_header_rule_ink_ratio", "paddle_header_rule_margin",
        "paddle_pos_search_chars", "paddle_separator_search_ratio",
        "paddle_separator_band_radius", "paddle_separator_roi_width_ratio",
        "paddle_separator_column_margin", "paddle_tesseract_psm",
        "paddle_alignment_y_tolerance_ratio", "paddle_alignment_min_similarity",
        "paddle_conflict_review_margin",
    )

DISPLAY_FIELDS = (
        "marker_height", "guide_width",
        "main_entry_font_family", "main_entry_font_size",
        "main_entry_width_chars", "main_entry_x_ratio",
        "review_entry_font_family", "review_entry_font_size",
        "review_entry_vertical_padding", "review_single_cjk_line_height",
        "review_zoom_percent", "wordslist_path",
    )

PROJECT_RUNTIME_FIELDS = (
        "batch_interval", "tesseract_language",
        "paddle_ocr_version", "paddle_max_input_side",
        "illustration_detect_padding", "illustration_detect_right_padding",
    )

EXPERT_FIELDS = (
        "layout_writing_mode", "layout_text_direction", "layout_transform",
        "layout_columns_policy", "layout_column_separator_mode",
        "paddle_language", "paddle_lens_timeout",
        "paddle_lens_default_confidence",
        "paddle_headword_regex", "paddle_pos_regex", "paddle_special_symbol_regex",
    )

SETTING_UNITS = {
        "columns": "栏",
        "start_y": "% 图高", "bottom_y": "原图px", "manual_x": "% 图宽",
        "column_width": "% 图宽", "gutter": "% 图宽", "body_indent": "% 图宽",
        "character_height": "% 图高", "row_padding": "% 图高", "horizontal_tolerance": "% 图宽",
        "darkness_threshold": "RGB 和", "dark_area_percent": "%",
        "ordinary_right_divisor": "1/x", "white_threshold_high": "0–1000",
        "white_threshold_low": "0–1000", "whitespace_adjustment": "原图px",
        "upward_ratio": "1/x", "analysis_left": "% 图宽", "analysis_right": "% 图宽",
        "row_step_multiplier": "×行高", "column_track_radius": "% 单栏宽",
        "column_track_block_height": "% 正文高度", "column_track_max_step": "% 分块高度",
        "paddle_band_width_ratio": "%", "paddle_band_left_margin": "原图px",
        "paddle_left_tolerance": "% 单栏宽", "paddle_max_input_side": "px",
        "paddle_separator_safety_px": "原图px", "paddle_separator_band_radius": "原图px",
        "paddle_separator_roi_width_ratio": "%", "paddle_separator_column_margin": "原图px",
        "paddle_header_search_height": "% 图高", "paddle_header_rule_margin": "原图px",
        "batch_interval": "秒", "illustration_detect_padding": "原图px",
        "illustration_detect_right_padding": "原图px", "main_entry_font_size": "pt",
        "review_entry_font_size": "pt", "review_entry_vertical_padding": "px",
        "review_single_cjk_line_height": "原图px", "review_zoom_percent": "%",
    }

SETTING_SPIN = {
        "columns": (1, 12, 1),
        "start_y": (0.0, 100.0, 0.05), "bottom_y": (0, 50000, 1),
        "manual_x": (0.0, 100.0, 0.05), "column_width": (0.01, 100.0, 0.05),
        "gutter": (0.0, 100.0, 0.05), "body_indent": (0.0, 100.0, 0.05),
        "character_height": (0.01, 100.0, 0.05), "row_padding": (0.0, 100.0, 0.05),
        "horizontal_tolerance": (0.0, 100.0, 0.05), "darkness_threshold": (0, 765, 1),
        "dark_area_percent": (1.0, 100.0, 0.1), "ordinary_right_divisor": (1.0, 5.0, 0.1),
        "white_threshold_high": (0, 1000, 1), "white_threshold_low": (0, 1000, 1),
        "whitespace_adjustment": (0, 30, 1), "upward_ratio": (0.1, 10.0, 0.1),
        "row_step_multiplier": (0.5, 3.0, 0.1),
        "analysis_left": (0.0, 100.0, 0.1), "analysis_right": (0.0, 100.0, 0.1),
        "column_track_radius": (0.5, 50.0, 0.5),
        "column_track_block_height": (0.5, 25.0, 0.5),
        "column_track_max_step": (0.5, 50.0, 0.5),
        "paddle_band_width_ratio": (1.0, 100.0, 0.1), "paddle_band_left_margin": (0, 5000, 1),
        "paddle_left_tolerance": (0.0, 100.0, 0.1), "paddle_max_input_side": (256, 20000, 64),
        "paddle_separator_safety_px": (0, 1000, 1),
        "paddle_separator_band_radius": (0, 200, 1),
        "paddle_separator_roi_width_ratio": (10.0, 100.0, 0.1),
        "paddle_separator_column_margin": (0, 2000, 1),
        "paddle_header_search_height": (0.0, 100.0, 0.1), "paddle_header_rule_margin": (0, 1000, 1),
        "batch_interval": (0.5, 3600, 0.5),
        "illustration_detect_padding": (0, 5000, 1),
        "illustration_detect_right_padding": (0, 5000, 1),
        "main_entry_font_size": (5, 200, 1), "review_entry_font_size": (6, 200, 1),
        "review_entry_vertical_padding": (0, 30, 1),
        "review_single_cjk_line_height": (0, 500, 1), "review_zoom_percent": (0.0, 250.0, 0.5),
    }

SETTING_HELP_IMAGES = {
        "columns": "layout_col_number.png",
        "start_y": "layout_settings.png",
        "bottom_y": "layout_settings.png",
        "manual_x": "layout_settings.png",
        "column_width": "layout_settings.png",
        "gutter": "layout_settings.png",
        "character_height": "layout_settings.png",
        "row_padding": "layout_settings.png",
    }

SETTING_CHOICES = {
        "analysis_threshold_mode": {
            "自动（推荐，等同 Otsu）": "auto",
            "Otsu 全页阈值": "otsu",
            "自适应（底色不均时）": "adaptive",
            "固定阈值（旧项目/专家）": "fixed",
        },
        "paddle_preprocessing": {
            "原图（推荐）": "original",
            "灰度": "grayscale",
            "自动对比度": "auto_contrast",
            "二值化": "binary",
        },
    }

CHECK_HELP = {
        "ordinary_auto_layout": "开启：每一页执行【普通画线】前先自动检测该页版面，再只用下方勾选的版面字段覆盖项目基准值，形成这一页专属的临时参数后再运行 VB 普通画线。页面之间互不污染。\n\n关闭：普通画线直接使用项目当前版面参数。",
        "ordinary_auto_columns": "自动版面检测后，用当前页检测出的【分栏数】临时替换项目基准值；只影响本页普通画线，不写回下一页。",
        "ordinary_auto_start_y": "自动版面检测后，用当前页检测出的【正文起始Y】临时替换项目基准值；适合页眉位置存在逐页漂移的扫描。",
        "ordinary_auto_manual_x": "自动版面检测后，用当前页检测出的【首栏X】临时替换项目基准值；适合整页左右轻微漂移。",
        "ordinary_auto_column_width": "自动版面检测后，用当前页检测出的【单栏宽】临时替换项目基准值；栏左跟随搜索范围也会按该页实际栏宽百分比计算。",
        "ordinary_auto_gutter": "自动版面检测后，用当前页检测出的【栏间空】临时替换项目基准值；只影响当前页几何。",
        "ordinary_auto_character_height": "自动版面检测后，用当前页检测出的【单行高】临时替换项目基准值；会影响普通画线的行尺度和跳步。",
        "ordinary_auto_row_padding": "自动版面检测后，用当前页检测出的【行间空】临时替换项目基准值；与单行高共同决定普通画线行尺度。",
        "follow_column_deformation": "开启：沿页面分块重新跟踪栏左缘，让栏路径可随书脊弯曲、斜拍或局部形变变化。三个相关参数现在都是相对量：搜索范围按单栏宽百分比、分块高度按正文高度百分比、最大局部斜率按分块高度百分比计算。\n\n关闭：栏左缘按较直的几何路径处理，平直扫描更稳定也更简单。",
        "paddle_use_paddleocr": "开启：PaddleOCR 作为 OCR画线的主文字识别来源。默认推荐，因为后续 grammar/parser、候选评分和多 OCR 融合都围绕结构化文字结果工作。\n\n关闭：仅用于专门测试其他引擎或故障排查；若同时没有可用 Tesseract/Lens，OCR画线将缺少主要文字来源。",
        "paddle_use_textline_orientation": "开启：让 PaddleOCR 额外处理文字行方向/旋转信息，适合文字行方向不稳定、局部旋转或特殊扫描。\n\n代价：通常增加计算并可能改变模型路径。普通已经规范化的横排/竖排页面不需要为了“更准”而默认开启，优先让 Project Profile 的页面变换处理整体方向。",
        "paddle_remove_syllable_separators": "开启：最终 lemma 归一化时去掉音节分隔点（如 ·、•、∙、‧），并对部分 OCR 分隔符误识别做保守清理；真正的单个词内连字符原则上保留。\n\n关闭：保留词头中的这些分隔符，适合词典索引本身就要求保留音节标记的项目。它改变输出 lemma 文本，不改变词头 Y。",
        "paddle_auto_header_rule": "开启：在页面顶部指定范围内寻找高横向墨迹占比的页眉横线，并把其上方内容排除出候选区。可减少 running header、页码等误词头。\n\n关闭：不做这套自动横线截断。若 Project Profile 已明确提供页眉模板，优先相信模板；第一条正文被误裁时检查搜索高度、墨迹比例和页眉后余量。",
        "paddle_enable_lens": "开启：允许 Google Lens 作为网络第三意见；实际何时调用、是否投票由【Lens 运行模式】决定。\n\n注意：会产生网络等待且依赖外部服务可用性。默认不应把 Lens 当成本地 OCR 的必需依赖，推荐仅在冲突模式下使用。",
        "paddle_require_visual_cue": "名称是历史遗留。当前实现并不是“必须有纯视觉证据”，而是要求候选至少有一个结构或视觉 fallback cue：POS/变形/描述符/特殊符号，或字高/粗体/行前空白之一。\n\n开启可抑制只有合法字母形态、却没有任何词条特征的正文行；关闭会放宽候选门槛，除非 diagnostics 明确显示真实词头因此被拒，否则不建议关闭。",
        "paddle_require_pos_or_symbol": "开启：普通词头候选必须具有至少一个强结构提示：POS、变形、结构描述符或可作为新词条证据的特殊符号。能显著抑制栏左正文误检。\n\n关闭：允许仅靠位置/视觉分数通过，召回更高但假阳性更多。对结构化拉丁词典通常建议开启；CJK/特殊 Profile 还会有自己的专用接受逻辑。",
        "paddle_refine_separator_y": "开启：OCR画线仍按原流程精修；普通画线则先完整执行 VB.NET 的向上白带定位，已经得到一个 VB 分隔 Y 后，才把现有局部墨迹谷算法作为最后的小范围二次修正，并限制最大移动量。它不再负责替代 VB 的初始 Y 定位。\n\n关闭：普通画线直接使用 VB 分隔 Y；OCR画线保留其未精修的粗定位。",
        "paddle_compare_tesseract": "开启：对同一候选带额外运行 Tesseract，作为 PaddleOCR 的第二意见并进入比较/诊断；需要 Tesseract 程序和相应语言包。\n\n影响：运行时间增加，但可暴露系统性字符差异。它本身不等于“允许 Tesseract 独有结果补线”，后者由【Tesseract 可补漏 Paddle】控制。",
        "paddle_tesseract_rescue": "开启：允许满足结构/位置条件的 Tesseract 独有候选补回 Paddle 漏掉的词头，而不只是做诊断对照。\n\n风险：可提高召回，也会引入 Tesseract 特有误检。建议先开启对照看 comparison/issues，再决定是否让其参与补漏。",
        "paddle_tesseract_auto_psm": "开启：程序自动比较 Tesseract PSM 4 与 PSM 6，选择更适合当前候选带的结果；减少手动猜 Page Segmentation Mode。\n\n关闭：固定使用【Tesseract 对照 PSM】。只有已验证某本词典某个 PSM 明显更稳定、且自动选择反复选错时才关闭。",
        "paddle_dual_ocr_arbitration": "开启：对 Paddle/Tesseract（以及可投票的 Lens）候选按 原图位置、lemma 相似度、结构与质量做融合/仲裁，而不是让某个引擎简单覆盖另一个。\n\n关闭：更接近单引擎/诊断式工作流。正常多 OCR 项目建议开启；需要复现实验性的单引擎结果时再关闭。",
        "paddle_show_candidate_checkboxes": "开启：主图为栏左 OCR 候选显示人工复选框，可把自动拒绝但合理的候选手工加入，也可取消自动接受结果；人工决定保存到独立 sidecar，便于追溯。\n\n关闭：界面更干净，但失去逐候选快速覆盖入口。只影响人工复核 UI，不重新运行 OCR。",
        "ocr_replace": "开启：普通文本 OCR 完成后执行项目替换规则，用于已知 OCR 拼写/字符归一化。这里说的是“已有词条线后的文本 OCR”，不是 OCR画线的词头 parser。\n\n关闭：保留 OCR 原始文本。排查替换规则是否误改内容时可暂时关闭。",
        "lowercase_ocr": "开启：普通文本 OCR 输出统一转为小写。只影响文本内容，不改变词头横线、坐标或 OCR画线候选。\n\n注意：专名、缩写或大小写具有词典意义的项目不应开启。它不是排序时的大小写折叠选项。",
        "review_main_show_ocr_choices": "开启：校对窗口打开时，主界面仍保留多 OCR 候选/选择控件，便于一边看校对行一边核对不同引擎结果。\n\n关闭：校对期间隐藏这些控件，使主界面更简洁。只影响显示，不清除候选数据。",
        "review_main_show_ocr_background": "开启：校对窗口打开时，主界面词条框仍按 OCR 置信度/状态显示底色，便于快速发现低可信项。\n\n关闭：校对期间使用更干净的统一显示。只改变视觉提示，不影响实际置信度或词条内容。",
        "main_entry_font_bold": "开启后主界面词条编辑框使用粗体；关闭为常规字重。只改变显示和预览字体，不会改变 OCR、PDIC、坐标或切图。",
        "main_entry_font_italic": "开启后主界面词条编辑框使用斜体；关闭为正体。仅影响显示。某些字体的斜体字宽会变化，可能让文本框视觉占用略有不同，但保存内容不变。",
        "review_entry_font_bold": "开启后校对窗口“原词条”编辑框使用粗体；关闭为常规字重。只影响校对文字显示和字体测量，不改变原图裁图或保存内容。",
        "review_entry_font_italic": "开启后校对窗口“原词条”编辑框使用斜体；关闭为正体。只影响显示；若某字体斜体导致字符更宽，可见字符数可能略变，但词条数据不变。",
    }

NORMAL_CHECKS = (
        ("自动精修横线 Y", "paddle_refine_separator_y"),
        ("跟随栏左缘倾斜/弯曲", "follow_column_deformation"),
        ("使用自动版面参数", "ordinary_auto_layout"),
        ("分栏数", "ordinary_auto_columns"),
        ("正文起始Y", "ordinary_auto_start_y"),
        ("首栏X", "ordinary_auto_manual_x"),
        ("单栏宽", "ordinary_auto_column_width"),
        ("栏间空", "ordinary_auto_gutter"),
        ("单行高", "ordinary_auto_character_height"),
        ("行间空", "ordinary_auto_row_padding"),
    )

OCR_COMMON_CHECKS = (
        ("PaddleOCR 主识别", "paddle_use_paddleocr"),
        ("同时运行 Tesseract 对照", "paddle_compare_tesseract"),
        ("多 OCR 自动融合", "paddle_dual_ocr_arbitration"),
        ("要求结构/视觉提示", "paddle_require_visual_cue"),
        ("要求词性/变形/词条符号", "paddle_require_pos_or_symbol"),
        ("自动精修横线 Y", "paddle_refine_separator_y"),
    )

OCR_ADVANCED_CHECKS = (
        ("启用文字行方向识别", "paddle_use_textline_orientation"),
        ("自动忽略页眉横线以上", "paddle_auto_header_rule"),
        ("去除词头音节分隔点", "paddle_remove_syllable_separators"),
        ("Tesseract 可补漏 Paddle", "paddle_tesseract_rescue"),
        ("Tesseract 自动比较 PSM 4/6", "paddle_tesseract_auto_psm"),
        ("显示每个 OCR 候选复选框", "paddle_show_candidate_checkboxes"),
    )

DISPLAY_STYLE_CHECKS = (
        ("主界面词条粗体", "main_entry_font_bold"),
        ("主界面词条斜体", "main_entry_font_italic"),
        ("校对词条粗体", "review_entry_font_bold"),
        ("校对词条斜体", "review_entry_font_italic"),
    )

DISPLAY_CHECKS = (
        ("校对时主界面显示 OCR 候选", "review_main_show_ocr_choices"),
        ("校对时主界面显示 OCR 置信度底色", "review_main_show_ocr_background"),
    )


__all__ = [
    "FIELDS",
    "PROFILE_FIELD_GROUPS",
    "PROFILE_CHECKS",
    "FIELD_GROUPS",
    "CHECK_GROUPS",
    "OCR_LANGUAGES",
    "SETTING_LABELS",
    "SETTING_HELP",
    "COMMON_FIELDS",
    "NORMAL_COMMON_FIELDS",
    "NORMAL_ADVANCED_FIELDS",
    "OCR_COMMON_FIELDS",
    "OCR_ADVANCED_FIELDS",
    "DISPLAY_FIELDS",
    "PROJECT_RUNTIME_FIELDS",
    "EXPERT_FIELDS",
    "SETTING_UNITS",
    "SETTING_SPIN",
    "SETTING_HELP_IMAGES",
    "SETTING_CHOICES",
    "CHECK_HELP",
    "NORMAL_CHECKS",
    "OCR_COMMON_CHECKS",
    "OCR_ADVANCED_CHECKS",
    "DISPLAY_STYLE_CHECKS",
    "DISPLAY_CHECKS",
]
